# Generated by Django 3.1.12 on 2024-11-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudadanos', '0002_auto_20241117_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudadano',
            options={'permissions': [('ver_mis_antecedentes', 'Puede ver sus propios antecedentes'), ('ver_antecedentes_civiles', 'Puede ver antecedentes civiles de otros')]},
        ),
    ]
